### ISSUE TITLE
Does not build with latest tree-sitter (v0.23)

### ISSUE THREAD

**Issue by alexaandru** [pinbraerts/tree-sitter-fastbuild#1]
Hello,

I have tried building it with the latest tree-sitter (with npx tree-sitter generate --no-bindings) and it just hangs (waited ~15 minutes), it never completes.

It does create grammar.json and nothing else beyond that. It's stuck at 100% CPU, 25MB RSS memory and just sits there and never completes. Even strace doesn't show anything at all.

If it helps there is one other parser that runs into the same issue as yours: https://github.com/wldmr/tree-sitter-ink/issues/8 and he tracked it down to some upstream issues: https://github.com/wldmr/tree-sitter-ink/issues/8#issuecomment-2343249849

Hope this helps!
Cheers!

**Comment by pinbraerts** [comment]
Hey, I've stumbled upon the same issues, it was mainly because poor/recursive grammar. I will check

**Comment by pinbraerts** [comment]
I guess bumping up the version of Tree-Sitter does the trick

**Comment by alexaandru** [comment]
Yup, looks like that worked :-) Cheers!
